---
- name: Prepare servers
  hosts: all
  become: true
  
  pre_tasks:
    - name: Synchronize datetime
      ansible.builtin.copy:
        src: /usr/share/zoneinfo/Europe/Moscow
        dest: /etc/localtime
    - name: Restart time service
      ansible.builtin.service:
        name: chronyd
        state: restarted

- name: Setup log server
  hosts: logservers
  become: true

  roles:
    - role: configure_log_rsyslog
    - role: configure_log_audit

- name: Setup web server
  hosts: webservers
  become: true

  pre_tasks:
    - name: Install epel
      ansible.builtin.yum:
        name: epel-release
        state: latest

  roles:
    - role: install_web_packages
    - role: configure_web_rsyslog
    - role: configure_web_audit
